server.port=8082
spring.r2dbc.url=localhost
spring.r2dbc.database=todo
spring.r2dbc.username=postgres
spring.r2dbc.password=123456
spring.main.allow-bean-definition-overriding=true
jwt.secret=58sfF3544rSFG90G

